### ISSUE TITLE
Bootstrap 3.4 / 4 Compatibility

### ISSUE THREAD

**Issue by noobindustrie** [Sideclick/BootstrapModalBundle#4]
Hello.
Is compatibility with Symfony 3.4 / 4 feasible / planned?

**Comment by RowanReid** [comment]
Sorry for late reply, we're releasing version 1.0 within the next couple of weeks which will include support Symfony 3.4 & Bootstrap 4.  Symfony 4 support coming later

**Comment by mrzenun212** [comment]
Hi, any update for Symfony 3.* compatibility?

**Comment by RowanReid** [comment]
We have implemented this locally and push the update through before the end of Jan.  Thanks for your interest!

**Comment by RowanReid** [comment]
Resolved - v1.0 released, thanks for your patience!
